name: API CI

on:
  push:
    paths:
      - packages/api/**
  pull_request:
    paths:
      - packages/api/**

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: |
          npm ci
          cd packages/api
          npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: |
          npm ci
          cd packages/api
          npm run build
